name: Robot Inmobiliario Automatico

on:
  schedule:
    # Corre todos los días a las 10:00 AM de Argentina (13:00 UTC)
    - cron: '0 13 * * *' 
  workflow_dispatch:      # Mantiene el botón manual activo

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias necesarias
        run: pip install -r requirements.txt

      - name: Ejecutar Robot
        env:
          # Vinculamos los nuevos secretos de Twilio y Google
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
        run: python scraper_ml.py
