name: Robot Inmobiliario Automatico

on:
  schedule:
    - cron: '0 * * * *' # Corre automáticamente cada 1 hora exacta
  workflow_dispatch:     # Mantiene activo el botón "Run workflow"

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias necesarias
        run: pip install -r requirements.txt

      - name: Ejecutar Robot
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper_ml.py
